### ISSUE TITLE
dnfdragora help plz friend

### ISSUE THREAD

**Issue by wqhjstudios** [fedberry/dnfdragora#1]
"dnf client error occurred:
g-io-error-quark:
GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36)"

running fedora 30 xfce x86_64. reboot, refresh, reinstall, no fix for the errors. having embarrassment bc im a noob. if u can help, i would surely appreciate it. thank u!!

**Comment by wqhjstudios** [comment]
oh man i am so sorry. i hope i didnt waste ur time. hope to see u soon.

**Comment by agrez** [comment]
No problem @wqhjstudios, From memory I think I removed the crash happy dnf-updater in Fedberry due to this bug. You might want to do the same thing in Fedora.......

BTW,  I've been using Linux for probably close to 20 years now and it still often makes me feel like a 'noob' :smile:. Don't give up!
